#!/bin/sh

clock=$(date '+%I')


#case "$clock" in
#	"00") icon="" ;;
# 	"01") icon="🕐" ;;
# 	"02") icon="🕑" ;;
# 	"03") icon="🕒" ;;
# 	"04") icon="🕓" ;;
# 	"05") icon="🕔" ;;
# 	"06") icon="🕕" ;;
# 	"07") icon="🕖" ;;
# 	"08") icon="🕗" ;;
# 	"09") icon="🕘" ;;
# 	"10") icon="🕙" ;;
# 	"11") icon="🕚" ;;
# 	"12") icon="🕛" ;;
#esac

icon=" " 

# 1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s|..27m|</span></b>|")" && notify-send "Appointments" "$(calcurse -d3)" ;;
case $BLOCK_BUTTON in
    1) notify-send "This Month" "$(cal)" ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
	3) "$TERMINAL" -e "$EDITOR" "$0" ;;
    4) notify-send " Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`" ;;
esac

#date "+%Y %b %d (%a) $icon%I:%M%p"
# date "+[  %a %d %b ] [  %I:%M %P ]"
date "+[  %a %d %b |  %I:%M%p ]"
